name: Deploy to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 使用するNode.jsのバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Vue.jsのビルドコマンドを実行

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # ビルド結果のディレクトリを指定
          publish_branch: gh-pages # GitHub Pagesのブランチを指定
          destination_folder: ${{ github.head_ref && format('/{0}', replaceAll(github.head_ref, '/', '_')) }} # ブランチ名をパスに含める（スラッシュはアンダースコアに置換）