name: Deploy to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]
  workflow_dispatch:

# 権限の設定
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 使用するNode.jsのバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # Vue.jsのビルドコマンドを実行
    
      - name: Determine Destination Folder
        run: echo "DESTINATION_FOLDER=${GITHUB_REF_NAME//\//_}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # ビルド結果のディレクトリを指定
          publish_branch: gh-pages # GitHub Pagesのブランチを指定
          destination_folder: ${{ env.DESTINATION_FOLDER }} # デプロイ先のフォルダ名を指定 